### ISSUE TITLE
Couldn't listen on 0.0.0.0:5900: [Errno 98] Address already in use.

### ISSUE THREAD

**Issue by r00tb3** [mattymcfatty/HoneyPi#10]
I completed the setup successfully and got the test email too then received this error

`twisted.internet.error.CannotListenError: Couldn't listen on 0.0.0.0:5900: [Errno 98] Address already in use.`

and later the follwoing email

```
 [-] You may just need to add a default logging rule to the
    'filter' 'INPUT' chain on abcd1234.  For more information,
    see the file "FW_HELP" in the psad sources directory or visit:

    http://www.cipherdyne.org/psad/docs/fwconfig.html
```
What does this mean? I'm new to firewall and iptables so dont know what it indiates exactly.

Pls, help!!

**Comment by mattymcfatty** [comment]
I think I got that error in my email too. You may be able to ignore it. Try nmapping or telnetting to your honeypot and seeing if you get any email alerts.

For 5900, are you running VNC on this rPI per chance? or perhaps the mattshoneypot.py program was ran twice?

**Comment by r00tb3** [comment]
> I think I got that error in my email too. You may be able to ignore it. Try nmapping or telnetting to your honeypot and seeing if you get any email alerts.
> 
> For 5900, are you running VNC on this rPI per chance? or perhaps the mattshoneypot.py program was ran twice?

I have vnc running I uninstalled VNC from my rPI also disabled vnc from raspi-config but still the service is running I think this is the fake service and I just need to probe it to check whether the honeypot works or not.

**Comment by r00tb3** [comment]
> I think I got that error in my email too. You may be able to ignore it. Try nmapping or telnetting to your honeypot and seeing if you get any email alerts.
> 
> For 5900, are you running VNC on this rPI per chance? or perhaps the mattshoneypot.py program was ran twice?

Yes, there was already the mattshoneypot.py running in the bg killed it and started the script again now everything working fine.
