### ISSUE TITLE
Not receiving alerts

### ISSUE THREAD

**Issue by pieterjk** [mattymcfatty/HoneyPi#11]
Hi Matt, Great application.

I use this on a Raspberry and have recently run into some issues. 

Unfortunately, I am not a programmer and do not know Linux very well to troubleshoot this issue.

I have set up a clean copy of Raspian Stretch and ran the script. Done the whole email set up through this but did not get a test mail. 

If I run echo "test" | ssmtp email@gmail.com I receive the mail.

If I do a port scan, I get nothing. 

Any advice for me?

**Comment by fabiosoft** [comment]
Same for me... the script is never executed... 
for testing purpose i also set chmod 775 file permission to the `.sh` script.

**Comment by mattymcfatty** [comment]
I switched from ssmtp to msmtp. Should be good now.
