### ISSUE TITLE
Support for msmtp?

### ISSUE THREAD

**Issue by CvW** [mattymcfatty/HoneyPi#12]
Good evening,
I wonder if you would consider adding support for msmtp, since ssmtp is allegedly no longer functional in Raspbian Buster? Is there a way to change a conf file somewhere to substitute msmtp for ssmtp? The former works great, the latter not at all for me.

**Comment by mattymcfatty** [comment]
Great idea! I'm looking into this now...

**Comment by mattymcfatty** [comment]
Thanks for the suggestion! I updated the install script to use msmtp.

**Comment by CvW** [comment]
You are awesome.  

That was one of the issues that prevented me from installing honeypi on buster.  Is honeypi buster-compatible now?  

I ask, since if it’s not buster compatible (no pressure, just an observation) then could you consider modifying your install pages to reflect what versions of raspbian your install is compatible with? 

Thank you again, 

Constantin.

**Comment by mattymcfatty** [comment]
It is now buster compatible :-) hope you find it useful!
