### ISSUE TITLE
Email configuration

### ISSUE THREAD

**Issue by BeakerBoy1971** [mattymcfatty/HoneyPi#13]
Can you just give a bit more guidance on how you see this being filled out, especially the root line, and whether the host line is correct.

Many thanks

root=
mailhub=smtp.gmail.com:587
hostname-gmail.com
UseSTARTTLS=YES
AuthUser=
AuthPass=
FromLineOverride=yes

**Comment by timwegenerDE** [comment]
The used ssmtp is deprecated in Buster. I don't get it to work, so maybe this is the problem? I don't get it to send mails whatever I enter in the config...

**Comment by timwegenerDE** [comment]
I installed msmtp and msmtp-mta, added the send mail to the "blink" script and changed the settings to flash a light. However it didn't work; I can send mails now, but nothing get triggered when a port scan runs. Looks like this project isn't working anymore...?

**Comment by BeakerBoy1971** [comment]
tim

Thanks for trying and Happy Christmas!!!

**Comment by newkton1** [comment]
Cannot get gmail notifications with set App Password working on Buster.  Anybody have a solution?

**Comment by mattymcfatty** [comment]
I'm going to look at getting msmtp working....stay tuned....

**Comment by mattymcfatty** [comment]
Got msmtp added to the install script. Cheers!
