### ISSUE TITLE
RPI4? and is this project still being worked on?

### ISSUE THREAD

**Issue by MarcGodard** [mattymcfatty/HoneyPi#15]
Hi, just wondering if this will work on a pi4?

Also, are the improvements talked about in https://trustfoundry.net/honeypi-easy-honeypot-raspberry-pi/ still being worked on?

I would like to create a gui for this like the pihole has (and a corresponding flutter app).

**Comment by mattymcfatty** [comment]
If you can get Rasbian on a Pi 4 then this should work. But I don't have a Pi4 to test this on.

I haven't been making improvements really. Mainly fixing stuff when updates break things. 

GUI improvements would be welcomed!

Cheers!
