### ISSUE TITLE
SSH log in

### ISSUE THREAD

**Issue by SunTzo** [mattymcfatty/HoneyPi#16]
First of all thanks. Got it installed and working. If I ping the ip or scan it with NMAP I get the emails. The question I have is, should I get an email when I ssh into the system?  I even use the wrong password and still didn't get an email. Is it working the way it' supposed to? I do get one if I try to VNC into the system.

**Comment by mattymcfatty** [comment]
great question! I have it set to ignore SSH so I won't get an alert every time I log in and mess with the honeypot. if you want to get notified on ssh connections, then open up /etc/psad/psad.conf and comment-out this line:

IGNORE_PORTS                tcp/22;
