### ISSUE TITLE
systemd-journal HIGH CPU when using torrent - please provide info to revert installation!!

### ISSUE THREAD

**Issue by c3kkos** [mattymcfatty/HoneyPi#18]
As mentioned in topic title, i have process systemd-journal eating up all my raspberrypi cpu... its pratically unusable...

i apt-removed psas which had very high cpu usage too... downloading torrent generate tons of connections and logging... please i want my raspberry pi usable again, tell us how to revert installation of honeypi or disable it!!!

**Comment by JavanXD** [comment]
You commented the same on my raspberry pi project which is designed to measure beehive data: https://github.com/Honey-Pi/HoneyPi/issues/5 Please create issues only for the projects you are using.

**Comment by mattymcfatty** [comment]
There is no uninstall script. Sorry. There is a disclaimer during install that states:

> _This install process will change some things on your Pi. Most notably, it will flush your iptables and turn up logging. There is no UNINSTALL script, so think hard about not doing this if you plan to use your Pi for other things._

Best I can recommend is restoring your Pi from the backup you made before accepting that disclaimer above.

I'm always happy to add improvements as well to this free and open source project. Submit a pull request with an uninstall script and I'd be happy to include it.
