### ISSUE TITLE
Adding IP Addresss to Email message

### ISSUE THREAD

**Issue by MyProjectExpert** [mattymcfatty/HoneyPi#6]
Great HoneyPot for my raspberry Pi.   How can I add my IP address to the email message when HoneyPot starts.  If you point me to right direction on modifying email messages, I can do this as well.

**Comment by mattymcfatty** [comment]
Hey Michael. The Source and Destination IPs should already be in the email messages. PSAD is the tool that does the detection and emailing. If you want additional information in the emails, I would look into customizing PSAD email messages. This link looks like it might be a good place to start https://github.com/mrash/psad/issues/13
