### ISSUE TITLE
Too Many Emails

### ISSUE THREAD

**Issue by justaGrad** [mattymcfatty/HoneyPi#7]
Hey Matt,

Firstly, thank you for releasing this project. I am currently in my last class and have to develop a honeypot device that can detect port scanning and some other malicious activities. Your project has been very helpful with this. 

My question today is regarding the email notifications. When I run an nmap scan against the server, I will get barraged with emails. Is it possible to edit a feature in PSAD to where I don't get spammed with emails? 

Edit: After going to the following link: http://cipherdyne.org/psad/docs/config.html#EMAIL_ADDRESSES

I was able to see the PORT_RANGE_SCAN_THRESHOLD configuration variable. I tried to play around with this but was wondering if you had any other ideas.

**Comment by mattymcfatty** [comment]
Hey! Glad to hear the project is useful to you.

On mine at home, I have the "PSAD_EMAIL_LIMIT" tuned down. 
http://cipherdyne.org/psad/docs/config.html#PSAD_EMAIL_LIMIT

I thought about tuning this down by default, but decided I would rather have a honeypot on the internal network more sensitive by default than less sensitive.

Hope this helps!

--Matt
